# Generated by Django 3.0.2 on 2020-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=150)),
                ('autores', models.CharField(max_length=200)),
                ('data_publicacao', models.DateField()),
                ('descricao', models.TextField()),
                ('numero_paginas', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
