# Generated by Django 3.0.2 on 2020-01-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_auto_20200115_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
