# Generated by Django 3.0.2 on 2020-01-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('livro', '0003_livro_editora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(to='categoria.Categoria'),
        ),
    ]
