# Generated by Django 3.0.2 on 2020-01-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='usario',
            new_name='usuario',
        ),
    ]
