# Generated by Django 3.0.2 on 2020-01-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_auto_20200115_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='valor_multa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
